# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy back-end & nginx configuration & front-end to Luidi's lb.unicusano.it site

on:
  push:
    branches:
      - lb.unicusano.it_Luigi
      
  workflow_dispatch:
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v2
        
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.UNICUSANO_HOST }}
          username: ${{ secrets.UNICUSANO_USER }}
          password: ${{ secrets.UNICUSANO_PASS }}
          port: ${{ secrets.UNICUSANO_PORT }}
          source: "Back/s2.py"
          target: "/var/www/stat/stat/"
