name: vclass-host.it

on:
  push:
    branches:
      -  vclass-host.it_Luigi
      
  workflow_dispatch:
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v2
        with:
          ref: vclass-host.it_Luigi
        
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VCLASS_HOST }}
          username: ${{ secrets.VCLASS_USER }}
          password: ${{ secrets.VCLASS_PASS }}
          port: ${{ secrets.VCLASS_PORT }}
          source: "Back/s2.py"
          target: "/var/www/stat/stat/"
